Verbose lnx error output
brave/go-translate pull request #47
Opened 2024-06-26 09:38 UTC by atuchin-m

If the container returns error then explicitly write about it in the response body.
This helps to diff go-translate issues from lnx container issues.

2024-07-01 14:02 UTC, atuchin-m commented on .github/workflows/ci.yml
> +        uses: golangci/golangci-lint-action@v6
This is supposed to be pinned right after merging this PR (that updates the actions)

2024-07-01 15:54 UTC, thypon requested changes

2024-07-01 15:54 UTC, thypon commented on .github/workflows/ci.yml
> +      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
here it's better to use the full version `4.1.7`

2024-07-01 15:54 UTC, thypon commented on .github/workflows/ci.yml
> +      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
```suggestion
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
```

2024-07-01 15:55 UTC, thypon commented on .github/workflows/ci.yml
> +        uses: golangci/golangci-lint-action@v6
```suggestion
        uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64 # v6.0.1
```

2024-07-01 17:33 UTC, thypon submitted a review, later dismissed

2024-07-02 09:55 UTC, linhkikuchi approved these changes

2024-07-02 09:57 UTC, merged